spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.100:3306/gulimall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: gulimall-product
  mail:
    host: smtp.qq.com
    port: 465
    username: 1932794922@qq.com
    #kxbmznmegsasbeab
    password: kxbmznmegsasbeab
    form: 1932794922@qq.com

  cloud:
    nacos:
      server-addr: 192.168.10.100:8848
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    host: 192.168.10.100
    port: 6379
  session:
    store-type: redis
    timeout: 3600


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.august.gulimall.*.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


server:
  port: 6001

gulimall:
  thread:
    core-size: 10
    max-size: 200
    keep-alive-time: 10
    queue-capacity: 10000
