spring:
  application:
    name: gulimall-third-party
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.100:3306/gulimall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: 192.168.10.100:8848




server:
  port: 30000

alibaba:
  cloud:
    oss:
      endpoint: xxxx
      bucket: xxx
    access-key: xxxxx
    secret-key: xxxx
    callback-url: http://127.0.0.1:30000/thirdparty/oss/callback


mail:
  host: smtp.qq.com
  port: 587
  username: xxxx
  #kxbmznmegsasbeab
  password: xxxxx
  from: xxxx