server:
  port: 88

spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      server-addr: 192.168.10.100:8848
    gateway:
      routes:
        #商品服务
        - id: gulimall_product
          uri: lb://gulimall-product
          order: 1
          predicates:
            - Path=/api/product/**
          filters:
            # 路径重新
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        #第三方服务
        - id: gulimall_third_party
          uri: lb://gulimall-third-party
          order: 2
          predicates:
            - Path=/api/thirdparty/**
          filters:
            # 路径重新
            - RewritePath=/api/thirdparty/?(?<segment>.*), /$\{segment}

        # 会员服务
        - id: gulimall-member
          uri: lb://gulimall-member
          order: 3
          predicates:
            - Path=/api/member/**
          filters:
            # 路径重新
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        # 仓储服务
        - id: gulimall-ware
          uri: lb://gulimall-ware
          order: 4
          predicates:
            - Path=/api/ware/**
          filters:
            # 路径重新
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        # es服务
        - id: gulimall-search
          uri: lb://gulimall-search
          order: 5
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        #优惠券服务
        - id: gulimall-coupon
          uri: lb://gulimall-coupon
          order: 5
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        #秒杀服务
        - id: gulimall-seckill
          uri: lb://gulimall-seckill
          order: 5
          predicates:
            - Path=/api/seckill/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        # 商品前台
        - id: gulimall_product_front
          uri: lb://gulimall-product
          order: 6
          predicates:
            - Host=xx.com,item.xx.com

        # 商品搜索
        - id: gulimall_search_front
          uri: lb://gulimall-search
          order: 7
          predicates:
            - Host=search.xx.com

        # 认证服务
        - id: gulimall-auth-server
          uri: lb://gulimall-auth-server
          order: 8
          predicates:
            - Host=auth.xx.com

        # 购物车服务
        - id: gulimall-cart
          uri: lb://gulimall-cart
          order: 9
          predicates:
            - Host=cart.xx.com

        # 购物车服务
        - id: gulimall-order
          uri: lb://gulimall-order
          order: 10
          predicates:
            - Host=order.xx.com

        # 后台管理服务
        - id: gulimall_admin
          uri: lb://gulimall-admin
          order: 20
          predicates:
            - Path=/api/**
          filters:
            # 路径重新
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
